create table CUSTOMER_RISK_RATING_PB
(
  ETL_DATE              VARCHAR2(6),
  STATUS                VARCHAR2(2),
  DATA_FLAG             VARCHAR2(64),
  CUSTOMER_BRANCH       VARCHAR2(20),
  CUSTOMER_SERIAL       VARCHAR2(64),
  OVERALL_RISK_RATING   VARCHAR2(200),
  LAST_RISK_RATING_DATE VARCHAR2(20)
);
comment on column CUSTOMER_RISK_RATING_PB.ETL_DATE
  is '上传月份';
comment on column CUSTOMER_RISK_RATING_PB.STATUS
  is '数据状态';
comment on column CUSTOMER_RISK_RATING_PB.DATA_FLAG
  is '数据标示';
comment on column CUSTOMER_RISK_RATING_PB.CUSTOMER_BRANCH
  is '客户分行';
comment on column CUSTOMER_RISK_RATING_PB.CUSTOMER_SERIAL
  is '客户系列';
comment on column CUSTOMER_RISK_RATING_PB.OVERALL_RISK_RATING
  is '综合风险评级';
comment on column CUSTOMER_RISK_RATING_PB.LAST_RISK_RATING_DATE
  is '最后风险评级日期';  
  
  
create table CUSTOMER_RISK_RATING_RBWM
(
  ETL_DATE              VARCHAR2(6),
  STATUS                VARCHAR2(2),
  DATA_FLAG             VARCHAR2(64),
  REVIEW_ID             VARCHAR2(64),
  CUSTOMER_NUMBER       VARCHAR2(64),
  CUSTOMER_TYPE         VARCHAR2(64),
  REVIEW_REASON         VARCHAR2(64),
  RISK_RATING           VARCHAR2(64),
  APPROVAL_CANCEL_DATE  VARCHAR2(20),            
  REVIEW_STATUS         VARCHAR2(32),
  CANCELLATION_REASON   VARCHAR2(200),
  CANCELLATION_COMMENTS VARCHAR2(4000),
  TRIGGER_DESCRIPTION   VARCHAR2(4000)
);
comment on column CUSTOMER_RISK_RATING_RBWM.ETL_DATE
  is '上传月份';
comment on column CUSTOMER_RISK_RATING_RBWM.STATUS
  is '数据状态';
comment on column CUSTOMER_RISK_RATING_RBWM.DATA_FLAG
  is '数据标示';
comment on column CUSTOMER_RISK_RATING_RBWM.REVIEW_ID
  is '审查ID';
comment on column CUSTOMER_RISK_RATING_RBWM.CUSTOMER_NUMBER
  is '客户编号';
comment on column CUSTOMER_RISK_RATING_RBWM.CUSTOMER_TYPE
  is '客户类型';  
comment on column CUSTOMER_RISK_RATING_RBWM.REVIEW_REASON
  is '审查原因';
comment on column CUSTOMER_RISK_RATING_RBWM.RISK_RATING
  is '风险评估';
comment on column CUSTOMER_RISK_RATING_RBWM.APPROVAL_CANCEL_DATE
  is '批准取消日期'; 
comment on column CUSTOMER_RISK_RATING_RBWM.REVIEW_STATUS
  is '检查状态';
comment on column CUSTOMER_RISK_RATING_RBWM.CANCELLATION_REASON
  is '注销原因';
comment on column CUSTOMER_RISK_RATING_RBWM.CANCELLATION_COMMENTS
  is '注销解释说明'; 
comment on column CUSTOMER_RISK_RATING_RBWM.TRIGGER_DESCRIPTION
  is '触发描述'; 
  
  
--菜单脚本
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS)
values ('19', '300号文文件上传/审核', null, 2, 1, '0', 8, null, '0', null, null, null, '1', null, null, null, null, null, null);
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS)
values ('1901', '300号文文件上传', '/fpages/export/ftl/UploadfilesFor300.jsp', 2, 0, '19', 1, '1', '1', null, null, null, '1', null, null, null, null, null, null);
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS)
values ('1902', '300号文文件审核', '/fpages/export/ftl/CheckfilesFor300.ftl', 2, 0, '19', 2, '1', '1', null, null, null, '1', null, null, null, null, null, null);
commit;

--TB_TABLEINFO_300脚本
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_PB', 'CUSTOMER_RISK_RATING_PB', 'CUSTOMER_BRANCH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_PB', 'CUSTOMER_RISK_RATING_PB', 'CUSTOMER_SERIAL', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_PB', 'CUSTOMER_RISK_RATING_PB', 'OVERALL_RISK_RATING', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_PB', 'CUSTOMER_RISK_RATING_PB', 'LAST_RISK_RATING_DATE', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'REVIEW_ID', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_NUMBER', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_TYPE', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'REVIEW_REASON', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'RISK_RATING', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'APPROVAL_CANCEL_DATE', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'REVIEW_STATUS', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'CANCELLATION_REASON', null, null, null, null, 8, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'CANCELLATION_COMMENTS', null, null, null, null, 9, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_RBWM', 'CUSTOMER_RISK_RATING_RBWM', 'TRIGGER_DESCRIPTION', null, null, null, null, 10, null, null, null, null);
commit;